import { StyleSheet } from "react-native";

const COLORS = {
    primary: '#5A9AA9',
    primaryDark: '#3d7a89',
    primaryLight: '#e8f4f7',
    background: '#f4f6f6',
    surface: '#ffffff',
    surfaceAlt: '#f9fbfb',
    border: '#dde3e5',
    borderFocus: '#5A9AA9',
    textPrimary: '#1a2e35',
    textSecondary: '#5f7a82',
    textMuted: '#9ab0b6',
    error: '#e05c5c',
    errorLight: '#fdf2f2',
    success: '#4caf82',
    successLight: '#f0faf5',
    warning: '#f59e0b',
    warningLight: '#fffbeb',
    shadow: '#1a2e35',
};

export const styles = StyleSheet.create({
    // ─── Layout ───────────────────────────────────────────────
    container: {
        flex: 1,
        justifyContent: 'center',
        padding: 24,
        backgroundColor: COLORS.background,
    },
    row: {
        alignItems: 'center',
        flexDirection: 'row',
    },
    card: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginVertical: 6,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
    },
    scrollContent: {
        paddingBottom: 32,
    },

    // ─── Typography ───────────────────────────────────────────
    title: {
        fontSize: 28,
        fontWeight: '700',
        letterSpacing: -0.5,
        color: COLORS.textPrimary,
        marginBottom: 8,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 15,
        fontWeight: '400',
        color: COLORS.textSecondary,
        textAlign: 'center',
        paddingHorizontal: 16,
        marginBottom: 24,
        lineHeight: 22,
    },
    text: {
        fontSize: 16,
        fontWeight: '400',
        color: COLORS.textPrimary,
        lineHeight: 24,
    },
    errorText: {
        color: COLORS.error,
        fontSize: 13,
        marginBottom: 10,
        marginLeft: 4,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.textPrimary,
        letterSpacing: -0.3,
    },
    caption: {
        fontSize: 12,
        color: COLORS.textMuted,
        fontWeight: '400',
    },

    // ─── Inputs ───────────────────────────────────────────────
    input: {
        backgroundColor: COLORS.surface,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 12,
        borderRadius: 12,
        fontSize: 15,
        color: COLORS.textPrimary,
    },
    textInput: {
        backgroundColor: COLORS.surface,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 15,
        color: COLORS.textPrimary,
        marginBottom: 10,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: COLORS.textSecondary,
        marginBottom: 6,
        marginLeft: 2,
    },

    // ─── Buttons ──────────────────────────────────────────────
    myButton: {
        backgroundColor: COLORS.primary,
        height: 42,
        marginVertical: 8,
        marginHorizontal: 0,
        justifyContent: 'center',
        borderRadius: 14,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 8,
        elevation: 4,
    },
    myButtonText: {
        fontWeight: '700',
        fontSize: 16,
        letterSpacing: 0.3,
        textAlign: 'center',
        color: '#ffffff',
    },
    mySmallButton: {
        paddingHorizontal: 8,
        paddingVertical: 6,
        margin: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    floatButton: {
        position: 'absolute',
        borderRadius: 28,
        width: 60,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.primary,
        elevation: 6,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        zIndex: 100,
    },
    floatButtonText: {
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
        color: '#ffffff',
    },
    outlineButton: {
        height: 48,
        marginVertical: 6,
        justifyContent: 'center',
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: COLORS.primary,
    },
    outlineButtonText: {
        fontWeight: '600',
        fontSize: 15,
        textAlign: 'center',
        color: COLORS.primary,
    },

    // ─── Cards & Containers ───────────────────────────────────
    textContainer: {
        marginHorizontal: 15,
        marginBottom: 10,
        borderColor: COLORS.border,
        borderTopWidth: 1.5,
        borderRadius: 5,
    },
    orderItem: {
        backgroundColor: COLORS.surface,
        padding: 14,
        marginHorizontal: 16,
        marginVertical: 6,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },

    // ─── Section ──────────────────────────────────────────────
    sectionContainer: {
        backgroundColor: COLORS.surface,
        borderRadius: 16,
        marginHorizontal: 16,
        marginVertical: 8,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: COLORS.border,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },

    // ─── Modal ────────────────────────────────────────────────
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(26, 46, 53, 0.5)',
    },
    modalContent: {
        width: '88%',
        backgroundColor: COLORS.surface,
        padding: 24,
        borderRadius: 20,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.textPrimary,
        marginBottom: 4,
    },
    modalSubtitle: {
        fontSize: 13,
        color: COLORS.textMuted,
        marginBottom: 16,
    },

    // ─── Misc Components ──────────────────────────────────────
    myMessagePopup: {
        padding: 14,
        position: 'absolute',
        top: 44,
        left: 0,
        right: 0,
        zIndex: 999,
        borderRadius: 12,
        marginHorizontal: 20,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 6,
    },
    myCircleLogo: {
        width: 110,
        height: 110,
        marginVertical: 24,
        borderRadius: 55,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 4,
    },

    // ─── Divider ──────────────────────────────────────────────
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 4,
    },
    sectionDivider: {
        height: 8,
        backgroundColor: COLORS.background,
    },
});

export { COLORS };